apiVersion: v1
kind: ConfigMap
metadata:
  name: module-configmap
  namespace: api-dev
data:
  module.json: | 
    {
      "url": "module",
      "resource_methods": ["GET", "POST", "OPTIONS"],
      "schema": {
        "name": {
          "type": "string",
          "required": true
        },
        "slug": {
          "type": "string",
          "required": true
        },
        "index": {
          "type": "integer"
        },
        "place": {
          "type": "string", 
          "required": true
        },
        "icon": {
          "type": "string", 
          "default": ""
        },
        "link": {
          "type": "string", 
          "default": ""
        },
        "description": {
          "type": "string", 
          "default": ""
        },
        "admin": {
          "type": "boolean", 
          "default": false
        },
        "locked": {
          "type": "boolean", 
          "default": false
        }
      }
    }