apiVersion: apps/v1
kind: Deployment
metadata:
  name: eve-go
  labels:
    app: eve-go
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eve-go
      version: v1
  template:
    metadata:
      labels:
        app: eve-go
        version: v1
    spec:
      containers:
      - name: eve-go
        image: gutorc92/eve-go:v0.0.1
        imagePullPolicy: Always
        env:
        - name: EVE_GO_URI
          value: 
        - name: EVE_GO_DATABASE
          value: eduqc
        - name: EVE_GO_FILES
          value: "/usr/json/"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /usr/json/
      volumes:
      - name: config-volume
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: module-configmap
          # items:
          # - key: module.json
          #   path: module.json
---
